Catkin-ProjectName: urdfdom
Version: 0.1.2
Release-Tag: 434

Depends: cmake,
    tinyxml,
    boost,
    pkg-config

Description: urdfdom is a parser and interface for the URDF

Author: John Hsu <johnhsu@willowgarage.com>
Maintainer: John Hsu <johnhsu@willowgarage.com>
Homepage: http://www.ros.org/wiki/urdf

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake

